### ISSUE TITLE
Add Article for Fibonacci in JavaScript

### ISSUE THREAD

**Issue by MariusGarbea** [TheRenegadeCoder/sample-programs-website#175]
See TheRenegadeCoder/sample-programs#484

**Comment by JamesS-M** [comment]
Hi I'd like to take this on. Could you assign it to me please?

**Comment by JamesS-M** [comment]
@jrg94 Maybe I'm misunderstanding something, but doesn't this article already exist? https://github.com/TheRenegadeCoder/sample-programs-website/blob/master/projects/fibonacci/_posts/_posts/2019-10-04-javascript.md

**Comment by jrg94** [comment]
You're right, it does! Looks like the link is broken though. I'll fix that now and close this.
