### ISSUE TITLE
Add Article for Reverse String in C++

### ISSUE THREAD

**Issue by Noah11012** [TheRenegadeCoder/sample-programs-website#201]
See TheRenegadeCoder/sample-programs#418

**Comment by SrushtiPatiL25** [comment]
is this issue closed??I would like to work on it..... can I ?

**Comment by jrg94** [comment]
As far as I can tell, this has never been done: https://sample-programs.therenegadecoder.com/projects/reverse-a-string/

It's all yours! Just make sure to refer to the code linked above.

**Comment by SrushtiPatiL25** [comment]
So does this mean that I have to code on command line and I cant use any editor?
Also, please can you attach contributing guidelines to it so that I can code accordingly...

**Comment by jrg94** [comment]
No, you shouldn't need to write code at all. The solution is already written: https://github.com/TheRenegadeCoder/sample-programs/blob/master/archive/c/c-plus-plus/reverse-string.cpp

Your job is to write an article explaining why it works.

**Comment by SrushtiPatiL25** [comment]
Ok cool. Sorry for the misunderstanding.
I'll try to do my job asap.

**Comment by SrushtiPatiL25** [comment]
Is there any prescribed format for explaining code...or just simply I 've to explain every line in code?

**Comment by jrg94** [comment]
The format is more or less up to you, but we recommend this template: https://github.com/TheRenegadeCoder/sample-programs-website/blob/master/templates/CODE_ARTICLE_TEMPLATE.md

**Comment by SrushtiPatiL25** [comment]
can u plz provide me any of sample description provided by anyone else...so that it will be easy for me to understand

**Comment by SrushtiPatiL25** [comment]
Hey, I referred to the fike that has been attached by you. For, implement solution section I had almost description for every line of code ready. But what to write in the section how to run?
It would be great if you can u brief me about that?

**Comment by jrg94** [comment]
Here's a list of existing C++ articles if you're interested: https://sample-programs.therenegadecoder.com/languages/c-plus-plus/

**Comment by SrushtiPatiL25** [comment]
Great! Tysm

**Comment by SrushtiPatiL25** [comment]
Great! Tysm
