### ISSUE TITLE
Add Article for Hello World in COBOL

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs-website#253]
Check out the code: TheRenegadeCoder/sample-programs#90

**Comment by Sudhanshu-Dubey14** [comment]
Hey @jrg94 
Can I write this article?
If yes, can you tell me what are the contents that you are looking for in this article?

**Comment by jrg94** [comment]
Yup! Here's the code you would be writing about: https://github.com/TheRenegadeCoder/sample-programs/blob/7682891c83b76aba3bf863366683a66b04a1b0c7/archive/c/cobol/hello-world.cbl

Here's the general template that we use: https://github.com/TheRenegadeCoder/sample-programs-website/blob/master/templates/CODE_ARTICLE_TEMPLATE.md
