### ISSUE TITLE
Add Depth First Search in Every Language Article

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs-website#327]
I realized that I'm playing with graph algorithms, but we never mentioned one of the most basic algorithms: dfs. Let's get a description going.

**Comment by mowies** [comment]
I am not quite sure I understand what the task is here. Could you explain it to me please?
What are the language articles exactly?

**Comment by jrg94** [comment]
Sure! Here's the quick summary:

- We document all of our projects before we let anyone commit to them. In this case, you meantioned DFS. We'd like to get that specified first.
- All examples of projects can be found here: https://sample-programs.therenegadecoder.com/projects/
- To make on, you'd need to submit a pull request with the following template filled out: https://github.com/TheRenegadeCoder/sample-programs-website/blob/master/templates/PROJECT_ARTICLE_TEMPLATE.md
- That template needs to be called `index.md`, and it needs to be placed in a folder with the name of your project here: https://github.com/TheRenegadeCoder/sample-programs-website/tree/master/projects

Let me know if you need more guidance!
