### ISSUE TITLE
Create Featured Image for Baklava in Every Language

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs-website#337]
As I begin to look through our website, I realize that a lot of the content lacks featured images. Perhaps we could start adding some. Here's the tool we use to generate images: https://github.com/TheRenegadeCoder/image-titler

Here's the article that needs an image: https://sample-programs.therenegadecoder.com/projects/baklava/

Feel free to be creative, but also make sure to use an image that's covered by Creative Commons (I recommend Pixabay).

**Comment by SvA1** [comment]
Hi @jrg94 . Do I get it right that you need an image for a specific section (e.g. Testing)?

**Comment by jrg94** [comment]
I need a featured image at the top. It's currently the default image.

**Comment by jrg94** [comment]
Oh this was closed by #345
