### ISSUE TITLE
Add Capitalize in Pascal Article

### ISSUE THREAD

**Issue by auroq** [TheRenegadeCoder/sample-programs-website#367]
Please link to the pull request that contains the related code snippet: https://github.com/TheRenegadeCoder/sample-programs/pull/2249

**Comment by smjalageri** [comment]
I need help on this Request 

#2249 is linked to closed Issue #2248

Should I edit 

the Pull Request 2249 
and replace 

- [X] I fixed #2248

with 
- [X] I fixed #367


Kindly help, is that the right way to link..

**Comment by jrg94** [comment]
No, the pull request is fine. This issue links to that pull request for reference. If you want to create the associated documentation, you'd make a pull request in this repo.
