### ISSUE TITLE
Add Prime Number in Pascal Article

### ISSUE THREAD

**Issue by auroq** [TheRenegadeCoder/sample-programs-website#369]
Please link to the pull request that contains the related code snippet: https://github.com/TheRenegadeCoder/sample-programs/pull/2242

**Comment by smjalageri** [comment]
> Please link to the pull request that contains the related code snippet: [TheRenegadeCoder/sample-programs#2242](https://github.com/TheRenegadeCoder/sample-programs/pull/2242)

Sir, 
I created the Pull Request without creating the Issue for Prime No. in Pascal. 
I'm Sorry.

I'm trying to link Issue 369 to PR 2242
