### ISSUE TITLE
Add Selection Sort in C Article

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs-website#427]
Please link to the pull request that contains the related code snippet: https://github.com/TheRenegadeCoder/sample-programs/pull/2039

**Comment by vansh-patel-8123** [comment]
hey, I want to contribute to this problem, can you assign me ?

**Comment by vansh-patel-8123** [comment]
Selection Sort is done !
[Pull request](https://github.com/TheRenegadeCoder/sample-programs-website/pull/483)
