### ISSUE TITLE
Add Coil Web Monetization to Author File

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs-website#453]
I just blanket added my own coil link to the site (see #452), but we could add a way for contributors to add their own wallets to posts that they've added. This could promote development on the site—who knows.

**Comment by rzuckerm** [comment]
I'm not sure "coil" is still a thing. Here's a letter from [Coil](https://www.coil.com/)

**Comment by jrg94** [comment]
Yeah, it's dead. Oh well!
