### ISSUE TITLE
Bug: Some languages have extraneous greater than sign at beginning of code sample

### ISSUE THREAD

**Issue by rzuckerm** [TheRenegadeCoder/sample-programs-website#502]
For example:
* [Baklava in Algol68](https://sampleprograms.io/projects/baklava/algol68/)
* [Hello World in Carp](https://sampleprograms.io/projects/hello-world/carp/)

It seems like if the language isn't recognized by the code formatter, it puts a `>` as the first character, even though the code sample doesn't start with that character. If you look at the corresponding `doc/index.md` files, you'll see what I mean:
* [Baklava in Algol68 docs/index.md](https://github.com/TheRenegadeCoder/sample-programs-website/blob/main/docs/projects/baklava/algol68/index.md)
* [Hello World in Carp docs/index.mk](https://github.com/TheRenegadeCoder/sample-programs-website/blob/main/docs/projects/hello-world/carp/index.md)

**Comment by jrg94** [comment]
Okay, here's the code sample that isn't rendering correctly:

```algol68
FOR n FROM -10 TO 10
DO
    INT num spaces := ABS n;
    printf(($gl$, " " * num spaces + "*" * (21 - 2*num spaces)))
OD
```

GitHub pages uses GFM (GitHub Flavored Markdown), so I expected the bug to be here as well. It's not. I'll have to look at the HTML source next.

**Comment by jrg94** [comment]
Going to drop some resources as I look deeper into this:
- [Jekyll Markdown Options](https://jekyllrb.com/docs/configuration/markdown/)
- [Kramdown GFM Parser Repo](https://github.com/kramdown/parser-gfm)

**Comment by jrg94** [comment]
Okay. It could have been some weird rendering bug. I removed the `markdown: GFM` line from config file, and the issue seems to be gone. I have no clue if my change fixed it or it was purely coincidental.
