### ISSUE TITLE
ROT13 Article Includes a Mistake in the Naming Convention

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs-website#504]
It looks like the article lists rot-13 in the code samples, but the reality is that rot13 seems to be the standard throughout the repo. I'll have to dig into this deeper, but that was what I noticed at a quick glance.

**Comment by rzuckerm** [comment]
This should be fixed now with 3c3ebca55973729367985a168e371eb4854ff129
