### ISSUE TITLE
Bug: Incorrect error message in Linear Search

### ISSUE THREAD

**Issue by rzuckerm** [TheRenegadeCoder/sample-programs-website#505]
The error message in [Linear Search](https://sampleprograms.io/projects/linear-search/) says this:
```
Usage: please provide a list of integers ("1, 4, 5, 11, 12") and the integer to find ("11")
```
According to the tests for this sample, the error message is actually this:
```
Usage: please provide a sorted list of integers ("1, 4, 5, 11, 12") and the integer to find ("11")
```
Granted that the former error message makes more sense given that a linear search doesn't care about the order. However, if the test were changed, that would break a bunch of tests.

**Comment by jrg94** [comment]
Ah, this is a strange one. I think this is my fault. I hastily put together the tests by copying over the binary search code. This is definitely an issue on the testing side, and I think it's a relatively easy fix. Can we keep the old error message and update the tests instead:

- [Link to Test File](https://github.com/TheRenegadeCoder/sample-programs/blob/main/test/projects/test_linear_search.py)
- [Link to Linear Search Page and 5 Programs with Solutions](https://sampleprograms.io/projects/linear-search/)

**Comment by rzuckerm** [comment]
@jrg94 Since there are only 5 code snippets, it wouldn't be too hard to change them all along with the test code. In order to get a valid GitHub Actions run, I'd have to do a PR with all 6 (or 7 when my Algol68 implementation is merged) files changed. This should be easy enough to do.
