### ISSUE TITLE
Add Even Odd in PHP Article

### ISSUE THREAD

**Issue by rzuckerm** [TheRenegadeCoder/sample-programs-website#604]

**Comment by harshitrajsinha** [comment]
Hello, @rzuckerm. Can you explain this issue as I can already see sample code in: docs/projects/even-odd/php/index.md

**Comment by rzuckerm** [comment]
Hello, @harshitrajsinha . There was a previous attempt to write an article for this sample program, and I created an issue for them. Unfortunately, it didn't work out. Yes, there is an [article](https://sampleprograms.io/projects/even-odd/php/), but it is just a placeholder. If you look at the "How to Implement the Solution" and "How to Run the Solution" sections, you'll see that they are blank. Please see the [Contributing Document](https://github.com/TheRenegadeCoder/sample-programs-website/blob/main/.github/CONTRIBUTING.md) for details on what is expected. If you wish to write this article, I'll assign it to you. If you would rather write code than write about code, then I would like to direct you to our [Sample Programs](https://github.com/TheRenegadeCoder/sample-programs) repository.
